name: Package Python application to EXE

on:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if (Test-Path -Path "requirements.txt") { pip install -r requirements.txt }

    - name: Install PyInstaller
      run: pip install pyinstaller

    - name: Package main.py to EXE with commit hash
      run: |
        $commitHash = "${{ github.sha }}".Substring(0, 7)
        $outputName = "main-$commitHash"
        pyinstaller --onefile --clean -F -w --name $outputName main.py
        echo "COMMIT_HASH=$commitHash" >> $env:GITHUB_ENV
        echo "OUTPUT_NAME=$outputName" >> $env:GITHUB_ENV

    - name: List files in dist directory
      run: |
        Get-ChildItem -Path dist -Recurse

    - name: Upload EXE file as artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.OUTPUT_NAME }}.exe
        path: dist/${{ env.OUTPUT_NAME }}.exe
