name: Package Python application to EXE

on:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if (Test-Path -Path "requirements.txt") { pip install -r requirements.txt }

    - name: Install PyInstaller
      run: pip install pyinstaller

    - name: Package main.py to EXE
      run: pyinstaller --onefile --clean main.py

    - name: Upload EXE file as artifact
      uses: actions/upload-artifact@v4
      with:
        name: main.exe
        path: dist/main.exe
