STANDARD_VCARD_FIELDS = [
    'UID', 'FN', 'N', 'EMAIL', 'TEL', 'VERSION', 'PHOTO',
    'BDAY', 'NOTE', 'ORG', 'TITLE', 'URL', 'ADR'
]

STANDARD_ICAL_FIELDS = [
    'UID', 'SUMMARY', 'LOCATION', 'DESCRIPTION', 'STATUS',
    'DTSTART', 'DTEND', 'RRULE', 'VALARM', 'CATEGORIES',
    'PRIORITY', 'TRANSP', 'ORGANIZER', 'SEQUENCE', 'URL',
    'ATTENDEE', 'VERSION', 'PRODID', 'X-ALLDAY', 'CREATED',
    'DTSTAMP', 'LAST-MODIFIED', 'COMPLETED', 'DUE',
    'X-FORCE-REMINDER', 'X-SYNC-TZ'
]
